#!/usr/bin/python

import subprocess
import os
import sys
import json
sys.path.insert(0, '/usr/local/munki')
sys.path.insert(0, '/usr/local/munkireport')
from Foundation import CFPreferencesCopyAppValue
from munkilib import FoundationPlist

def get_pref_value(key, domain):
    value = CFPreferencesCopyAppValue(key, domain)
    if(value is not None):
        return value
    elif(value is not None and len(value) == 0):
        return ""
    else:
        return ""

def main():
    """Main"""
    # Create cache dir if it does not exist
    cachedir = '%s/cache' % os.path.dirname(os.path.realpath(__file__))
    if not os.path.exists(cachedir):
        os.makedirs(cachedir)

    data = {}
    try:
        micromdm_ver="1.1.1"
        data["micromdm_version"] = micromdm_ver
    except:
        data["micromdm_version"] = "Not Installed"
    try:
        cmd = ["/usr/bin/profiles", "status", "-type", "enrollment"]
        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        stdout, _ = proc.communicate()
        if stdout:
            enrollment = stdout
    except (IOError, OSError):
        pass
    for line in enrollment.splitlines():
        items = line.split(":")
        if items[0] == "Enrolled via DEP":
            data["dep_enrollment_status"] = items[1].strip()
        if items[0] == "MDM enrollment":
            data["mdm_enrollment_status"] = items[1].strip()
    print(data)
    # Write memory results to cache
    output_file = os.path.join(cachedir, 'micromdm.json')
    with open(output_file, 'w') as fp:
        json.dump(data, fp, indent=4, sort_keys=True)

if __name__ == "__main__":
    main()
